"""column name changed

Revision ID: 07a2430fdf94
Revises: a680e1d5c6c3
Create Date: 2025-02-13 21:23:53.418046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a2430fdf94'
down_revision: Union[str, None] = 'a680e1d5c6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'deleted')
    # ### end Alembic commands ###
