"""unique constraint added to docker_id

Revision ID: 789f5e35f2a9
Revises: 8d583e8cbce5
Create Date: 2025-03-10 23:51:46.972836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789f5e35f2a9'
down_revision: Union[str, None] = '8d583e8cbce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_server_container_name', 'containers', type_='unique')
    op.create_unique_constraint('uq_server_docker', 'containers', ['server_id', 'docker_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_server_docker', 'containers', type_='unique')
    op.create_unique_constraint('uq_server_container_name', 'containers', ['server_id', 'name'])
    # ### end Alembic commands ###
