"""unique constraint added to user_id in refresh token model

Revision ID: 64390bd15c7b
Revises: 6d174a851bf2
Create Date: 2025-04-11 23:03:31.140915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64390bd15c7b'
down_revision: Union[str, None] = '6d174a851bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_refresh_tokens_user_id', 'refresh_tokens', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_refresh_tokens_user_id', 'refresh_tokens', type_='unique')
    # ### end Alembic commands ###
