"""unique constraint changed to indexes with soft-delete support

Revision ID: a408f99d05fc
Revises: 078d4f54962f
Create Date: 2025-03-12 14:50:57.149537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a408f99d05fc'
down_revision: Union[str, None] = '078d4f54962f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_server_container_name', 'containers', type_='unique')
    op.create_index('uq_server_container_name', 'containers', ['server_id', 'name'], unique=True, postgresql_where='deleted = false')
    op.drop_constraint('uq_server_docker', 'containers', type_='unique')
    op.create_index('uq_server_docker', 'containers', ['server_id', 'docker_id'], unique=True, postgresql_where='deleted = false')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_server_docker', table_name='containers', postgresql_where='deleted = false')
    op.create_unique_constraint('uq_server_docker', 'containers', ['server_id', 'docker_id'])
    op.drop_index('uq_server_container_name', table_name='containers', postgresql_where='deleted = false')
    op.create_unique_constraint('uq_server_container_name', 'containers', ['server_id', 'name'])
    # ### end Alembic commands ###
