"""updated_at column added to serverorm model

Revision ID: 3421ddb83d8e
Revises: bb92f4162a74
Create Date: 2025-03-05 21:04:09.306927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3421ddb83d8e'
down_revision: Union[str, None] = 'bb92f4162a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'updated_at')
    # ### end Alembic commands ###
