"""deleted columnd added to container model

Revision ID: 117ab3b048a1
Revises: 6563f0cb3a26
Create Date: 2025-03-06 20:04:05.654953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117ab3b048a1'
down_revision: Union[str, None] = '6563f0cb3a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'deleted')
    # ### end Alembic commands ###
