"""unique constraint fix

Revision ID: 302166eeaeb5
Revises: 789f5e35f2a9
Create Date: 2025-03-11 00:09:00.989503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302166eeaeb5'
down_revision: Union[str, None] = '789f5e35f2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_server_container_name', 'containers', ['server_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_server_container_name', 'containers', type_='unique')
    # ### end Alembic commands ###
